### ISSUE TITLE
MyPage, DetailPage 프로필 사진 비율 수정

### ISSUE THREAD

**Issue by ars-yeon** [Sesco-nb13/contact-app#104]
## Todo

 1. MyPage, DetailPage 프로필 사진 비율 수정
  - [x] AppBarLayout: layout_heigh를 `wrap_content`로 수정

  - AppCompatImageView
    - [x] layout_heigh을 `wrap_content`로 수정
    - [x] `adjustViewBouds = true` 추가
