### ISSUE TITLE
코드 리팩토링

### ISSUE THREAD

**Issue by LordOfWins** [Sesco-nb13/contact-app#57]
## Todo

 - [ ] 1. 코드를 주석화 한 것은 지운다.

 - [ ] 2. 중괄호가 비어있는 메서드는 = Unit을 대입한다.
 
 - [ ] 3.  importantForAccessibility, contentDescription은 기입해준다.
